version: '3.5'

services:

  ##
  #
  # Generic node
  #
  ##
  eth-main:
    build:
      context: .
      dockerfile: Dockerfile.main
    image: pee/eth-main

  ##
  #
  # Base development image
  #
  ##
  eth-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: pee/eth-dev

  ##
  #
  # boot node to link up network
  #
  ##
  bootnode:
    build:
      context: .
      dockerfile: Dockerfile.bootnode
    image: pee/eth-dev-boot
    container_name: eth-dev-boot
    restart: on-failure:10
    networks:
      - circlejerk
    ports:
        - 8545
        - 30301/tcp
        - 30301/udp
        - 30303
    environment:
      - RUN_BOOTNODE=true
    volumes:
      - bootShare:/boot
    command: --verbosity=2



  ##
  #
  #
  #
  ##
  rpcnode:
    build:
      context: .
      dockerfile: Dockerfile.rpcnode
    image: pee/eth-dev-rpc

  ##
  #
  #
  #
  ##
  worknode:
    build:
      context: .
      dockerfile: Dockerfile.worknode
    image: pee/eth-dev-worker

  ##
  #
  #
  #
  ##
  minernode:
    build:
      context: .
      dockerfile: Dockerfile.minernode
    image: pee/eth-dev-miner




##
#
#
#
##
