version: '3.4'
services:
  go-ethereum:
    build:
      context: ./
      dockerfile: Dockerfile
    image: pee/go-ethereum
    container_name: ethereum_main
    restart: 'true'
    ports:
      - "8545:8545"
      - "30303:30303"
    restart: on-failure:10
    user: $UID
    entrypoint: /usr/local/bin/geth --rpc --rpcaddr 0.0.0.0





